// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table internal header
//
// Internal details; most calling programs do not need this header,
// unless using verilator public meta comments.

#ifndef VERILATED_VTB_PC3_XOR__SYMS_H_
#define VERILATED_VTB_PC3_XOR__SYMS_H_  // guard

#include "verilated.h"

// INCLUDE MODEL CLASS

#include "Vtb_pc3_xor.h"

// INCLUDE MODULE CLASSES
#include "Vtb_pc3_xor___024root.h"
#include "Vtb_pc3_xor___024unit.h"
#include "Vtb_pc3_xor_activation32__Kz6.h"
#include "Vtb_pc3_xor_mulRecFN__E8_S18.h"
#include "Vtb_pc3_xor_hf_f2rec32.h"
#include "Vtb_pc3_xor_addRecFN__E8_S18.h"
#include "Vtb_pc3_xor_mulAddRecFN__E8_S18.h"

// DPI TYPES for DPI Export callbacks (Internal use)

// SYMS CLASS (contains all model state)
class alignas(VL_CACHE_LINE_BYTES)Vtb_pc3_xor__Syms final : public VerilatedSyms {
  public:
    // INTERNAL STATE
    Vtb_pc3_xor* const __Vm_modelp;
    VlDeleter __Vm_deleter;
    bool __Vm_didInit = false;

    // MODULE INSTANCE STATE
    Vtb_pc3_xor___024root          TOP;
    Vtb_pc3_xor___024unit          TOP____024unit;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__DOT__U_ONE;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__DOT__U_ZERO;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__DOT__U_ONE;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__DOT__U_ZERO;
    Vtb_pc3_xor_addRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ADD_BACKSUM;
    Vtb_pc3_xor_mulAddRecFN__E8_S18 TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__FMA_PRED;
    Vtb_pc3_xor_mulAddRecFN__E8_S18 TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__FMA_STATE;
    Vtb_pc3_xor_mulAddRecFN__E8_S18 TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__FMA_W;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_BACKIN__BRA__0__KET____DOT__u_b;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_THETA_PRESET__BRA__0__KET____DOT__u_p;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_THETA_PRESET__BRA__1__KET____DOT__u_p;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_XREC__BRA__0__KET____DOT__u_xr;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_XREC__BRA__1__KET____DOT__u_xr;
    Vtb_pc3_xor_mulRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__MUL_AE;
    Vtb_pc3_xor_mulRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__MUL_BACKJ;
    Vtb_pc3_xor_mulRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__MUL_BACK_GATE;
    Vtb_pc3_xor_mulRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__MUL_BLR;
    Vtb_pc3_xor_addRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__SUB_BME;
    Vtb_pc3_xor_addRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__SUB_ERR;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_A;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_BIAS_INIT;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_G;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_REC_BLR;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_REC_ONE;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_REC_ZERO;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_UI0;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_XOBS;
    Vtb_pc3_xor_activation32__Kz6  TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE;
    Vtb_pc3_xor_mulAddRecFN__E8_S18 TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__FMA;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__0__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__0__KET____DOT__UM;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__1__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__1__KET____DOT__UM;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__2__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__2__KET____DOT__UM;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__3__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__3__KET____DOT__UM;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__4__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__4__KET____DOT__UM;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__5__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__5__KET____DOT__UM;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__6__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__6__KET____DOT__UM;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__7__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__7__KET____DOT__UM;
    Vtb_pc3_xor_addRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__NEG_X;
    Vtb_pc3_xor_addRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__NEG_Y;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__U0;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__UBP0;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__UBP1;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__UBP2;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__UBP3;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__UBP4;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__UBP5;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__UBP6;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__UBP7;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__UBP8;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__UCLIP;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__U_ONE;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__U_ZERO;
    Vtb_pc3_xor_activation32__Kz6  TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE;
    Vtb_pc3_xor_mulAddRecFN__E8_S18 TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__FMA;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__0__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__0__KET____DOT__UM;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__1__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__1__KET____DOT__UM;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__2__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__2__KET____DOT__UM;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__3__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__3__KET____DOT__UM;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__4__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__4__KET____DOT__UM;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__5__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__5__KET____DOT__UM;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__6__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__6__KET____DOT__UM;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__7__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__7__KET____DOT__UM;
    Vtb_pc3_xor_addRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__NEG_X;
    Vtb_pc3_xor_addRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__NEG_Y;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__U0;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__UBP0;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__UBP1;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__UBP2;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__UBP3;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__UBP4;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__UBP5;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__UBP6;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__UBP7;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__UBP8;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__UCLIP;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__U_ONE;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__U_ZERO;
    Vtb_pc3_xor_addRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ADD_BACKSUM;
    Vtb_pc3_xor_mulAddRecFN__E8_S18 TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__FMA_PRED;
    Vtb_pc3_xor_mulAddRecFN__E8_S18 TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__FMA_STATE;
    Vtb_pc3_xor_mulAddRecFN__E8_S18 TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__FMA_W;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_BACKIN__BRA__0__KET____DOT__u_b;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_THETA_PRESET__BRA__0__KET____DOT__u_p;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_THETA_PRESET__BRA__1__KET____DOT__u_p;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_XREC__BRA__0__KET____DOT__u_xr;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_XREC__BRA__1__KET____DOT__u_xr;
    Vtb_pc3_xor_mulRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__MUL_AE;
    Vtb_pc3_xor_mulRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__MUL_BACKJ;
    Vtb_pc3_xor_mulRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__MUL_BACK_GATE;
    Vtb_pc3_xor_mulRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__MUL_BLR;
    Vtb_pc3_xor_addRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__SUB_BME;
    Vtb_pc3_xor_addRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__SUB_ERR;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_A;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_BIAS_INIT;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_G;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_REC_BLR;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_REC_ONE;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_REC_ZERO;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_UI0;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_XOBS;
    Vtb_pc3_xor_activation32__Kz6  TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE;
    Vtb_pc3_xor_mulAddRecFN__E8_S18 TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__FMA;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__0__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__0__KET____DOT__UM;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__1__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__1__KET____DOT__UM;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__2__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__2__KET____DOT__UM;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__3__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__3__KET____DOT__UM;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__4__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__4__KET____DOT__UM;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__5__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__5__KET____DOT__UM;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__6__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__6__KET____DOT__UM;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__7__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__7__KET____DOT__UM;
    Vtb_pc3_xor_addRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__NEG_X;
    Vtb_pc3_xor_addRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__NEG_Y;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__U0;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__UBP0;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__UBP1;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__UBP2;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__UBP3;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__UBP4;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__UBP5;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__UBP6;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__UBP7;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__UBP8;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__G_TANH__DOT__U_TANH__DOT__UCLIP;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__U_ONE;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__U_ZERO;
    Vtb_pc3_xor_activation32__Kz6  TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE;
    Vtb_pc3_xor_mulAddRecFN__E8_S18 TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__FMA;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__0__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__0__KET____DOT__UM;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__1__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__1__KET____DOT__UM;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__2__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__2__KET____DOT__UM;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__3__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__3__KET____DOT__UM;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__4__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__4__KET____DOT__UM;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__5__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__5__KET____DOT__UM;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__6__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__6__KET____DOT__UM;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__7__KET____DOT__UB;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__G_MB__BRA__7__KET____DOT__UM;
    Vtb_pc3_xor_addRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__NEG_X;
    Vtb_pc3_xor_addRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__NEG_Y;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__U0;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__UBP0;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__UBP1;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__UBP2;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__UBP3;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__UBP4;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__UBP5;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__UBP6;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__UBP7;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__UBP8;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__G_TANH__DOT__U_TANH__DOT__UCLIP;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__U_ONE;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__U_ZERO;
    Vtb_pc3_xor_addRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ADD_BACKSUM;
    Vtb_pc3_xor_mulAddRecFN__E8_S18 TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__FMA_PRED;
    Vtb_pc3_xor_mulAddRecFN__E8_S18 TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__FMA_STATE;
    Vtb_pc3_xor_mulAddRecFN__E8_S18 TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__FMA_W;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__G_BACKIN__BRA__0__KET____DOT__u_b;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__G_THETA_PRESET__BRA__0__KET____DOT__u_p;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__G_THETA_PRESET__BRA__1__KET____DOT__u_p;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__G_XREC__BRA__0__KET____DOT__u_xr;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__G_XREC__BRA__1__KET____DOT__u_xr;
    Vtb_pc3_xor_mulRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__MUL_AE;
    Vtb_pc3_xor_mulRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__MUL_BACKJ;
    Vtb_pc3_xor_mulRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__MUL_BACK_GATE;
    Vtb_pc3_xor_mulRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__MUL_BLR;
    Vtb_pc3_xor_addRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__SUB_BME;
    Vtb_pc3_xor_addRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__SUB_ERR;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_A;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_BIAS_INIT;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_G;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_REC_BLR;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_REC_ONE;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_REC_ZERO;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_UI0;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_XOBS;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__DOT__U_ONE;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__DOT__U_ZERO;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__DOT__U_ONE;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__DOT__U_ZERO;
    Vtb_pc3_xor_addRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ADD_BACKSUM;
    Vtb_pc3_xor_mulAddRecFN__E8_S18 TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__FMA_PRED;
    Vtb_pc3_xor_mulAddRecFN__E8_S18 TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__FMA_STATE;
    Vtb_pc3_xor_mulAddRecFN__E8_S18 TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__FMA_W;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_BACKIN__BRA__0__KET____DOT__u_b;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_BACKIN__BRA__1__KET____DOT__u_b;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_THETA_PRESET__BRA__0__KET____DOT__u_p;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_THETA_PRESET__BRA__1__KET____DOT__u_p;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_XREC__BRA__0__KET____DOT__u_xr;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_XREC__BRA__1__KET____DOT__u_xr;
    Vtb_pc3_xor_mulRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__MUL_AE;
    Vtb_pc3_xor_mulRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__MUL_BACKJ;
    Vtb_pc3_xor_mulRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__MUL_BACK_GATE;
    Vtb_pc3_xor_mulRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__MUL_BLR;
    Vtb_pc3_xor_addRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__SUB_BME;
    Vtb_pc3_xor_addRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__SUB_ERR;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_A;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_BIAS_INIT;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_G;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_REC_BLR;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_REC_ONE;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_REC_ZERO;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_UI0;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_XOBS;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__DOT__U_ONE;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__DOT__U_ZERO;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__DOT__U_ONE;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__DOT__U_ZERO;
    Vtb_pc3_xor_addRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ADD_BACKSUM;
    Vtb_pc3_xor_mulAddRecFN__E8_S18 TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__FMA_PRED;
    Vtb_pc3_xor_mulAddRecFN__E8_S18 TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__FMA_STATE;
    Vtb_pc3_xor_mulAddRecFN__E8_S18 TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__FMA_W;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__G_BACKIN__BRA__0__KET____DOT__u_b;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__G_BACKIN__BRA__1__KET____DOT__u_b;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__G_THETA_PRESET__BRA__0__KET____DOT__u_p;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__G_THETA_PRESET__BRA__1__KET____DOT__u_p;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__G_XREC__BRA__0__KET____DOT__u_xr;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__G_XREC__BRA__1__KET____DOT__u_xr;
    Vtb_pc3_xor_mulRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__MUL_AE;
    Vtb_pc3_xor_mulRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__MUL_BACKJ;
    Vtb_pc3_xor_mulRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__MUL_BACK_GATE;
    Vtb_pc3_xor_mulRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__MUL_BLR;
    Vtb_pc3_xor_addRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__SUB_BME;
    Vtb_pc3_xor_addRecFN__E8_S18   TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__SUB_ERR;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_A;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_BIAS_INIT;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_G;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_REC_BLR;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_REC_ONE;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_REC_ZERO;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_UI0;
    Vtb_pc3_xor_hf_f2rec32         TOP__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_XOBS;

    // SCOPE NAMES
    VerilatedScope __Vscope_tb_pc3_xor;
    VerilatedScope __Vscope_tb_pc3_xor__csv_open;
    VerilatedScope __Vscope_tb_pc3_xor__do_tick;

    // CONSTRUCTORS
    Vtb_pc3_xor__Syms(VerilatedContext* contextp, const char* namep, Vtb_pc3_xor* modelp);
    ~Vtb_pc3_xor__Syms();

    // METHODS
    const char* name() { return TOP.name(); }
};

#endif  // guard
