// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Primary model header
//
// This header should be included by all source files instantiating the design.
// The class here is then constructed to instantiate the design.
// See the Verilator manual for examples.

#ifndef VERILATED_VTB_PC3_XOR_H_
#define VERILATED_VTB_PC3_XOR_H_  // guard

#include "verilated.h"
#include "svdpi.h"

class Vtb_pc3_xor__Syms;
class Vtb_pc3_xor___024root;
class Vtb_pc3_xor___024unit;
class Vtb_pc3_xor_activation32__Kz6;
class Vtb_pc3_xor_addRecFN__E8_S18;
class Vtb_pc3_xor_hf_f2rec32;
class Vtb_pc3_xor_mulAddRecFN__E8_S18;
class Vtb_pc3_xor_mulRecFN__E8_S18;


// This class is the main interface to the Verilated model
class alignas(VL_CACHE_LINE_BYTES) Vtb_pc3_xor VL_NOT_FINAL : public VerilatedModel {
  private:
    // Symbol table holding complete model state (owned by this class)
    Vtb_pc3_xor__Syms* const vlSymsp;

  public:

    // CONSTEXPR CAPABILITIES
    // Verilated with --trace?
    static constexpr bool traceCapable = false;

    // PORTS
    // The application code writes and reads these signals to
    // propagate new values into/out from the Verilated model.

    // CELLS
    // Public to allow access to /* verilator public */ items.
    // Otherwise the application code can consider these internals.
    Vtb_pc3_xor___024unit* const __PVT____024unit;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_REC_ZERO;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_REC_ONE;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_REC_BLR;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_A;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_G;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_XOBS;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_UI0;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_BIAS_INIT;
    Vtb_pc3_xor_addRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ADD_BACKSUM;
    Vtb_pc3_xor_mulRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__MUL_BACK_GATE;
    Vtb_pc3_xor_mulAddRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__FMA_PRED;
    Vtb_pc3_xor_addRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__SUB_ERR;
    Vtb_pc3_xor_mulRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__MUL_AE;
    Vtb_pc3_xor_addRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__SUB_BME;
    Vtb_pc3_xor_mulAddRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__FMA_STATE;
    Vtb_pc3_xor_mulRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__MUL_BLR;
    Vtb_pc3_xor_mulAddRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__FMA_W;
    Vtb_pc3_xor_mulRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__MUL_BACKJ;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_THETA_PRESET__BRA__0__KET____DOT__u_p;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_THETA_PRESET__BRA__1__KET____DOT__u_p;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_XREC__BRA__0__KET____DOT__u_xr;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_XREC__BRA__1__KET____DOT__u_xr;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_BACKIN__BRA__0__KET____DOT__u_b;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__DOT__U_ONE;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__DOT__U_ZERO;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__DOT__U_ONE;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__0__KET____DOT__G_LAYER_INST_L0__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__DOT__U_ZERO;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_REC_ZERO;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_REC_ONE;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_REC_BLR;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_A;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_G;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_XOBS;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_UI0;
    Vtb_pc3_xor_activation32__Kz6* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_BIAS_INIT;
    Vtb_pc3_xor_activation32__Kz6* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE;
    Vtb_pc3_xor_addRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ADD_BACKSUM;
    Vtb_pc3_xor_mulRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__MUL_BACK_GATE;
    Vtb_pc3_xor_mulAddRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__FMA_PRED;
    Vtb_pc3_xor_addRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__SUB_ERR;
    Vtb_pc3_xor_mulRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__MUL_AE;
    Vtb_pc3_xor_addRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__SUB_BME;
    Vtb_pc3_xor_mulAddRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__FMA_STATE;
    Vtb_pc3_xor_mulRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__MUL_BLR;
    Vtb_pc3_xor_mulAddRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__FMA_W;
    Vtb_pc3_xor_mulRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__MUL_BACKJ;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_THETA_PRESET__BRA__0__KET____DOT__u_p;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_THETA_PRESET__BRA__1__KET____DOT__u_p;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_XREC__BRA__0__KET____DOT__u_xr;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_XREC__BRA__1__KET____DOT__u_xr;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_BACKIN__BRA__0__KET____DOT__u_b;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_REC_ZERO;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_REC_ONE;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_REC_BLR;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_A;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_G;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_XOBS;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_UI0;
    Vtb_pc3_xor_activation32__Kz6* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_BIAS_INIT;
    Vtb_pc3_xor_activation32__Kz6* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE;
    Vtb_pc3_xor_addRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ADD_BACKSUM;
    Vtb_pc3_xor_mulRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__MUL_BACK_GATE;
    Vtb_pc3_xor_mulAddRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__FMA_PRED;
    Vtb_pc3_xor_addRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__SUB_ERR;
    Vtb_pc3_xor_mulRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__MUL_AE;
    Vtb_pc3_xor_addRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__SUB_BME;
    Vtb_pc3_xor_mulAddRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__FMA_STATE;
    Vtb_pc3_xor_mulRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__MUL_BLR;
    Vtb_pc3_xor_mulAddRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__FMA_W;
    Vtb_pc3_xor_mulRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__MUL_BACKJ;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__G_THETA_PRESET__BRA__0__KET____DOT__u_p;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__G_THETA_PRESET__BRA__1__KET____DOT__u_p;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__G_XREC__BRA__0__KET____DOT__u_xr;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__G_XREC__BRA__1__KET____DOT__u_xr;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__1__KET____DOT__G_LAYER_INST_L1__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__G_BACKIN__BRA__0__KET____DOT__u_b;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_REC_ZERO;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_REC_ONE;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_REC_BLR;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_A;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_G;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_XOBS;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_UI0;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__U_BIAS_INIT;
    Vtb_pc3_xor_addRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ADD_BACKSUM;
    Vtb_pc3_xor_mulRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__MUL_BACK_GATE;
    Vtb_pc3_xor_mulAddRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__FMA_PRED;
    Vtb_pc3_xor_addRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__SUB_ERR;
    Vtb_pc3_xor_mulRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__MUL_AE;
    Vtb_pc3_xor_addRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__SUB_BME;
    Vtb_pc3_xor_mulAddRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__FMA_STATE;
    Vtb_pc3_xor_mulRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__MUL_BLR;
    Vtb_pc3_xor_mulAddRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__FMA_W;
    Vtb_pc3_xor_mulRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__MUL_BACKJ;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_THETA_PRESET__BRA__0__KET____DOT__u_p;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_THETA_PRESET__BRA__1__KET____DOT__u_p;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_XREC__BRA__0__KET____DOT__u_xr;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_XREC__BRA__1__KET____DOT__u_xr;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_BACKIN__BRA__0__KET____DOT__u_b;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__G_BACKIN__BRA__1__KET____DOT__u_b;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__DOT__U_ONE;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_STATE__DOT__U_ZERO;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__DOT__U_ONE;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__0__KET____DOT__u_core__DOT__ACT_PRE__DOT__U_ZERO;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_REC_ZERO;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_REC_ONE;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_REC_BLR;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_A;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_G;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_XOBS;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_UI0;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__U_BIAS_INIT;
    Vtb_pc3_xor_addRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ADD_BACKSUM;
    Vtb_pc3_xor_mulRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__MUL_BACK_GATE;
    Vtb_pc3_xor_mulAddRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__FMA_PRED;
    Vtb_pc3_xor_addRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__SUB_ERR;
    Vtb_pc3_xor_mulRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__MUL_AE;
    Vtb_pc3_xor_addRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__SUB_BME;
    Vtb_pc3_xor_mulAddRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__FMA_STATE;
    Vtb_pc3_xor_mulRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__MUL_BLR;
    Vtb_pc3_xor_mulAddRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__FMA_W;
    Vtb_pc3_xor_mulRecFN__E8_S18* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__MUL_BACKJ;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__G_THETA_PRESET__BRA__0__KET____DOT__u_p;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__G_THETA_PRESET__BRA__1__KET____DOT__u_p;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__G_XREC__BRA__0__KET____DOT__u_xr;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__G_XREC__BRA__1__KET____DOT__u_xr;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__G_BACKIN__BRA__0__KET____DOT__u_b;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__G_BACKIN__BRA__1__KET____DOT__u_b;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__DOT__U_ONE;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_STATE__DOT__U_ZERO;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__DOT__U_ONE;
    Vtb_pc3_xor_hf_f2rec32* const __PVT__tb_pc3_xor__DOT__uut__DOT__G_LAYER__BRA__2__KET____DOT__G_LAYER_INST_LX__DOT__L__DOT__G_NEURON__BRA__1__KET____DOT__u_core__DOT__ACT_PRE__DOT__U_ZERO;

    // Root instance pointer to allow access to model internals,
    // including inlined /* verilator public_flat_* */ items.
    Vtb_pc3_xor___024root* const rootp;

    // CONSTRUCTORS
    /// Construct the model; called by application code
    /// If contextp is null, then the model will use the default global context
    /// If name is "", then makes a wrapper with a
    /// single model invisible with respect to DPI scope names.
    explicit Vtb_pc3_xor(VerilatedContext* contextp, const char* name = "TOP");
    explicit Vtb_pc3_xor(const char* name = "TOP");
    /// Destroy the model; called (often implicitly) by application code
    virtual ~Vtb_pc3_xor();
  private:
    VL_UNCOPYABLE(Vtb_pc3_xor);  ///< Copying not allowed

  public:
    // API METHODS
    /// Evaluate the model.  Application must call when inputs change.
    void eval() { eval_step(); }
    /// Evaluate when calling multiple units/models per time step.
    void eval_step();
    /// Evaluate at end of a timestep for tracing, when using eval_step().
    /// Application must call after all eval() and before time changes.
    void eval_end_step() {}
    /// Simulation complete, run final blocks.  Application must call on completion.
    void final();
    /// Are there scheduled events to handle?
    bool eventsPending();
    /// Returns time at next time slot. Aborts if !eventsPending()
    uint64_t nextTimeSlot();
    /// Trace signals in the model; called by application code
    void trace(VerilatedTraceBaseC* tfp, int levels, int options = 0) { contextp()->trace(tfp, levels, options); }
    /// Retrieve name of this model instance (as passed to constructor).
    const char* name() const;

    // Abstract methods from VerilatedModel
    const char* hierName() const override final;
    const char* modelName() const override final;
    unsigned threads() const override final;
    /// Prepare for cloning the model at the process level (e.g. fork in Linux)
    /// Release necessary resources. Called before cloning.
    void prepareClone() const;
    /// Re-init after cloning the model at the process level (e.g. fork in Linux)
    /// Re-allocate necessary resources. Called after cloning.
    void atClone() const;
  private:
    // Internal functions - trace registration
    void traceBaseModel(VerilatedTraceBaseC* tfp, int levels, int options);
};

#endif  // guard
